---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp:
  labels:
    app: nginx
  name: nginx
  annotations:
    fluxcd.io/automated: 'true'
    fluxcd.io/automated_msg: test
    fluxcd.io/automated_user: Muhammad Hanzala <muhammadhanzala12@gmail.com>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1-alpine-perl
        name: nginx
        resources: {}
